export const ActionTypes = {

    //Products
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",

    //Authentication
    SET_AUTHENTICATED_USER: "SET_AUTHENTICATED_USER",
    REGISTER_USER: "REGISTER_USER",
    REFRESH_TOKEN: "REFRESH_TOKEN",
    SET_REFRESHED_TOKEN: "SET_REFRESHED_TOKEN",

    LOGOUT_USER_REQUEST: "LOGOUT_USER_REQUEST",
    LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
    LOGOUT_USER_FAILURE: "LOGOUT_USER_FAILURE",

    //Authentication V2
    AUTHENTICATE_USER_REQUEST: "AUTHENTICATE_USER_REQUEST",
    AUTHENTICATE_USER_SUCCESS: "AUTHENTICATE_USER_SUCCESS",
    AUTHENTICATE_USER_FAILURE: "AUTHENTICATE_USER_FAILURE",

    //Authentication Verify-2fa
    SET_TEMP_AUTHENTICATED_USER: "SET_TEMP_AUTHENTICATED_USER",
    SET_VERIFY_PIN_CODE: "SET_VERIFY_PIN_CODE",

    //Authentication Verify-2fa v2
    VERIFY_PIN_CODE_REQUEST: "VERIFY_PIN_CODE_REQUEST",
    VERIFY_PIN_CODE_SUCCESS: "VERIFY_PIN_CODE_SUCCESS",
    VERIFY_PIN_CODE_FAILURE: "VERIFY_PIN_CODE_FAILURE",

    // Accounts
    // Resend Pin Code
    RESEND_PIN_CODE_REQUEST: "RESEND_PIN_CODE_REQUEST",
    RESEND_PIN_CODE_SUCCESS: "RESEND_PIN_CODE_SUCCESS",
    RESEND_PIN_CODE_FAILURE: "RESEND_PIN_CODE_FAILURE",
    // Forgot Password
    FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
    FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
    FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",
    // Reset Password
    RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
    RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
    RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",
    // Change Password
    CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",
    // Verify Email
    VERIFY_NEW_CONTACT_MEDIA_REQUEST: "VERIFY_NEW_CONTACT_MEDIA_REQUEST",
    VERIFY_NEW_CONTACT_MEDIA_SUCCESS: "VERIFY_NEW_CONTACT_MEDIA_SUCCESS",
    VERIFY_NEW_CONTACT_MEDIA_FAILURE: "VERIFY_NEW_CONTACT_MEDIA_FAILURE",
    // Change Email
    CHANGE_EMAIL_REQUEST: "CHANGE_EMAIL_REQUEST",
    CHANGE_EMAIL_SUCCESS: "CHANGE_EMAIL_SUCCESS",
    CHANGE_EMAIL_FAILURE: "CHANGE_EMAIL_FAILURE",
    // Change Phone Number
    CHANGE_PHONE_NUMBER_REQUEST: "CHANGE_PHONE_NUMBER_REQUEST",
    CHANGE_PHONE_NUMBER_SUCCESS: "CHANGE_PHONE_NUMBER_SUCCESS",
    CHANGE_PHONE_NUMBER_FAILURE: "CHANGE_PHONE_NUMBER_FAILURE",

    // User preferences
    UPDATE_USER_PREFERENCES_REQUEST: "UPDATE_USER_PREFERENCES_REQUEST",
    UPDATE_USER_PREFERENCES_FAILURE: "UPDATE_USER_PREFERENCES_FAILURE",
    UPDATE_USER_PREFERENCES_SUCCESS: "UPDATE_USER_PREFERENCES_SUCCESS",
    GET_USER_PREFERENCES_REQUEST: "GET_USER_PREFERENCES_REQUEST",
    GET_USER_PREFERENCES_FAILURE: "GET_USER_PREFERENCES_FAILURE",
    GET_USER_PREFERENCES_SUCCESS: "GET_USER_PREFERENCES_SUCCESS",

    // Users
    WHO_I_AM_REQUEST: "WHO_I_AM_REQUEST",
    WHO_I_AM_SUCCESS: "WHO_I_AM_SUCCESS",
    
    USER_REQUEST: "USER_REQUEST",
    USER_SUCCESS: "USER_SUCCESS",
    USER_FAILURE: "USER_FAILURE",

    USERS_REQUEST: "USERS_REQUEST",
    USERS_SUCCESS: "USERS_SUCCESS",
    USERS_FAILURE: "USERS_FAILURE",

    UPDATE_USER_REQUEST: "UPDATE_USER_REQUEST",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",

    ADD_USER_REQUEST: "ADD_USER_REQUEST",
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    ADD_USER_FAILURE: "ADD_USER_FAILURE",

    DELETE_USER_REQUEST: "DELETE_USER_REQUEST",
    DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
    DELETE_USER_FAILURE: "DELETE_USER_FAILURE",

    LOCK_USER_REQUEST: "LOCK_USER_REQUEST",
    LOCK_USER_SUCCESS: "LOCK_USER_SUCCESS",
    LOCK_USER_FAILURE: "LOCK_USER_FAILURE",

    RESET_PASSWORD_USER_REQUEST: "RESET_PASSWORD_USER_REQUEST",
    RESET_PASSWORD_USER_SUCCESS: "RESET_PASSWORD_USER_SUCCESS",
    RESET_PASSWORD_USER_FAILURE: "RESET_PASSWORD_USER_FAILURE",

    // My Profile
    UPDATE_MY_PROFILE_REQUEST: "UPDATE_MY_PROFILE_REQUEST",
    UPDATE_MY_PROFILE_FAILURE: "UPDATE_MY_PROFILE_FAILURE",
    UPDATE_MY_PROFILE_SUCCESS: "UPDATE_MY_PROFILE_SUCCESS",
    GET_MY_PROFILE_REQUEST: "GET_MY_PROFILE_REQUEST",
    GET_MY_PROFILE_FAILURE: "GET_MY_PROFILE_FAILURE",
    GET_MY_PROFILE_SUCCESS: "GET_MY_PROFILE_SUCCESS",

    
    // Tenant preferences
    DELETE_TENANTS_REQUEST: "DELETE_TENANTS_REQUEST",
    DELETE_TENANTS_FAILURE: "DELETE_TENANTS_FAILURE",
    DELETE_TENANTS_SUCCESS: "DELETE_TENANTS_SUCCESS",

    UPDATE_TENANT_REQUEST: "UPDATE_TENANT_REQUEST",
    UPDATE_TENANT_FAILURE: "UPDATE_TENANT_FAILURE",
    UPDATE_TENANT_SUCCESS: "UPDATE_TENANT_SUCCESS",

    ADD_TENANT_REQUEST: "ADD_TENANT_REQUEST",
    ADD_TENANT_FAILURE: "ADD_TENANT_FAILURE",
    ADD_TENANT_SUCCESS: "ADD_TENANT_SUCCESS",

    GET_TENANT_REQUEST: "GET_TENANT_REQUEST",
    GET_TENANT_FAILURE: "GET_TENANT_FAILURE",
    GET_TENANT_SUCCESS: "GET_TENANT_SUCCESS",
    
    GET_TENANTS_REQUEST: "GET_TENANTS_REQUEST",
    GET_TENANTS_FAILURE: "GET_TENANTS_FAILURE",
    GET_TENANTS_SUCCESS: "GET_TENANTS_SUCCESS",

    EXPORT_PDF_TENANTS_REQUEST: "EXPORT_PDF_TENANTS_REQUEST",
    EXPORT_PDF_TENANTS_FAILURE: "EXPORT_PDF_TENANTS_FAILURE",
    EXPORT_PDF_TENANTS_SUCCESS: "EXPORT_PDF_TENANTS_SUCCESS",

    
    
    // Tenant preferences
    DELETE_AGENCIES_REQUEST: "DELETE_AGENCIES_REQUEST",
    DELETE_AGENCIES_FAILURE: "DELETE_AGENCIES_FAILURE",
    DELETE_AGENCIES_SUCCESS: "DELETE_AGENCIES_SUCCESS",

    UPDATE_AGENCY_REQUEST: "UPDATE_AGENCY_REQUEST",
    UPDATE_AGENCY_FAILURE: "UPDATE_AGENCY_FAILURE",
    UPDATE_AGENCY_SUCCESS: "UPDATE_AGENCY_SUCCESS",

    ADD_AGENCY_REQUEST: "ADD_AGENCY_REQUEST",
    ADD_AGENCY_FAILURE: "ADD_AGENCY_FAILURE",
    ADD_AGENCY_SUCCESS: "ADD_AGENCY_SUCCESS",

    GET_AGENCY_REQUEST: "GET_AGENCY_REQUEST",
    GET_AGENCY_FAILURE: "GET_AGENCY_FAILURE",
    GET_AGENCY_SUCCESS: "GET_AGENCY_SUCCESS",
    
    GET_AGENCIES_REQUEST: "GET_AGENCIES_REQUEST",
    GET_AGENCIES_FAILURE: "GET_AGENCIES_FAILURE",
    GET_AGENCIES_SUCCESS: "GET_AGENCIES_SUCCESS",

    //Server notifications
    SET_SERVER_NOTIFICATIONS: "SET_SERVER_NOTIFICATIONS",
    REMOVE_SERVER_NOTIFICATION: "REMOVE_SERVER_NOTIFICATION",

    //Languages
    GET_LANGUAGES: "GET_LANGUAGES",
    SET_LANGUAGES: "SET_LANGUAGES",

    GET_LANGUAGES_REQUEST: "GET_LANGUAGES_REQUEST",
    GET_LANGUAGES_SUCCESS: "GET_LANGUAGES_SUCCESS",
    GET_LANGUAGES_FAILURE: "GET_LANGUAGES_FAILURE",

    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",


    // Permanent Notification Message
    SET_NOTIFICATION_STATUS: "SET_NOTIFICATION_STATUS",
    COUNT_PERMANENT_NOTIFICATION: "COUNT_PERMANENT_NOTIFICATION",
    COUNT_PERMANENT_NOTIFICATION_SUCCESS: "COUNT_PERMANENT_NOTIFICATION_SUCCESS",

    GET_NOTIFICATIONS_REQUEST: "GET_NOTIFICATION_REQUEST",
    GET_NOTIFICATIONS_SUCCESS: "GET_NOTIFICATION_SUCCESS",
    GET_NOTIFICATIONS_FAILURE: "GET_NOTIFICATION_FAILURE",

    MARK_READ_NOTIFICATIONS_REQUEST: "MARK_READ_NOTIFICATIONS_REQUEST",
    MARK_READ_NOTIFICATIONS_SUCCESS: "MARK_READ_NOTIFICATIONS_SUCCESS",
    MARK_READ_NOTIFICATIONS_FAILURE: "MARK_READ_NOTIFICATIONS_FAILURE",

    DELETE_NOTIFICATIONS_REQUEST: "DELETE_NOTIFICATIONS_REQUEST",
    DELETE_NOTIFICATIONS_SUCCESS: "DELETE_NOTIFICATIONS_SUCCESS",
    DELETE_NOTIFICATIONS_FAILURE: "DELETE_NOTIFICATIONS_FAILURE",

    GRID_NOTIFICATIONS_FILTER_REQUEST: "GRID_NOTIFICATIONS_FILTER_REQUEST",
    GRID_NOTIFICATIONS_SORTING_REQUEST: "GRID_NOTIFICATIONS_SORTING_REQUEST",
    GRID_NOTIFICATIONS_PAGER_REQUEST: "GRID_NOTIFICATIONS_PAGER_REQUEST",
    
    GRID_NOTIFICATIONS_FILTER: "GRID_NOTIFICATIONS_FILTER",
    GRID_NOTIFICATIONS_SORTING: "GRID_NOTIFICATIONS_SORTING",
    GRID_NOTIFICATIONS_PAGER: "GRID_NOTIFICATIONS_PAGER",

    // Application Settings

    GET_APP_SETTINGS_REQUEST: "GET_APP_SETTINGS_REQUEST",
    GET_APP_SETTINGS_SUCCESS: "GET_APP_SETTINGS_SUCCESS",
    GET_APP_SETTINGS_FAILURE: "GET_APP_SETTINGS_FAILURE",

    UPDATE_APP_SETTINGS_REQUEST: "UPDATE_APP_SETTINGS_REQUEST",
    UPDATE_APP_SETTINGS_SUCCESS: "UPDATE_APP_SETTINGS_SUCCESS",
    UPDATE_APP_SETTINGS_FAILURE: "UPDATE_APP_SETTINGS_FAILURE",

}